#!/usr/bin/env bash
#
# Regenerate the three byte-exact corpus fixtures.
#
# These files cannot be authored with a normal editor: every editor on this
# machine will helpfully "fix" a CRLF file, strip a BOM, or add the missing
# final newline. So they are generated by `printf` with explicit escapes and
# verified byte-for-byte here.
#
# Run from anywhere:
#     ./scripts/build-byte-exact-fixtures.sh
#
# The script is idempotent and prints an `od -c` dump of each result so a human
# can confirm the bytes are what the file name claims.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
corpus="${repo_root}/crates/espansoconfig-core/tests/corpus/synthetic"
mkdir -p "${corpus}"

# ---------------------------------------------------------------------------
# 1. CRLF line endings, including inside a literal block scalar.
#
# YAML normalises line breaks to LF when it decodes a scalar, so the decoded
# value of the block below differs from its source bytes. Any code that writes
# a decoded value straight back would silently convert this file to LF.
# ---------------------------------------------------------------------------
crlf="${corpus}/crlf-line-endings.yml"
printf '%s\r\n' \
  '# CRLF fixture — every line break in this file is \r\n.' \
  '# Do NOT let an editor normalise it. See README.md in this directory.' \
  'matches:' \
  '  - trigger: :crlf' \
  '    replace: single line with a CRLF terminator' \
  '' \
  '  - trigger: :crlf-block' \
  '    replace: |' \
  '      first block line' \
  '      second block line' \
  '' \
  '  - trigger: :crlf-quoted' \
  "    replace: 'quoted value, CRLF after it'" \
  > "${crlf}"

# ---------------------------------------------------------------------------
# 2. UTF-8 BOM (EF BB BF) at the very start of the file.
#
# Espanso tolerates a BOM. We must strip it before parsing, remember it, and
# write it back on save — dropping it is a one-byte data loss that shows up as
# a diff in the user's git history.
# ---------------------------------------------------------------------------
bom="${corpus}/bom-utf8.yml"
{
  printf '\xEF\xBB\xBF'
  printf '%s\n' \
    '# UTF-8 BOM fixture — the first three bytes are EF BB BF.' \
    '# Do NOT let an editor strip them. See README.md in this directory.' \
    'matches:' \
    '  - trigger: :bom' \
    "    replace: 'the file starts with a byte-order mark'" \
    '  - trigger: :bom-acentos' \
    "    replace: 'áéíóú after a BOM'"
} > "${bom}"

# ---------------------------------------------------------------------------
# 3. No trailing newline.
#
# The last byte is `'`, not \n. A save that appends a newline "to be tidy"
# breaks the byte-identity guarantee on a file the user never edited.
# ---------------------------------------------------------------------------
no_newline="${corpus}/no-trailing-newline.yml"
{
  printf '%s\n' \
    '# No-trailing-newline fixture — the last byte of this file is an' \
    "# apostrophe, not a line feed. Do NOT let an editor add one." \
    'matches:' \
    '  - trigger: :no-final-newline'
  printf '%s' "    replace: 'the last line has no terminator'"
} > "${no_newline}"

# ---------------------------------------------------------------------------
# 4. Unicode offset-counting probe.
#
# The second sequence element must be a DECOMPOSED e + U+0301, not a
# precomposed U+00E9. Typing it in an editor, or letting one "clean up" the
# file, silently normalises it to NFC — and that destroys the only case that
# separates Unicode scalar values from grapheme clusters.
# ---------------------------------------------------------------------------
unicode="${corpus}/unicode-offsets.yml"
{
  printf '%s\n' \
    '# Offset-counting probe. Do NOT normalise this file.' \
    '# Element 1 is PRECOMPOSED U+00E9. Element 2 is DECOMPOSED U+0065 U+0301.' \
    '# Element 3 is U+1F600, outside the Basic Multilingual Plane.' \
    '# Together they distinguish byte / scalar-value / UTF-16 / grapheme offsets.'
  printf 'probe: [\xC3\xA9, e\xCC\x81, \xF0\x9F\x98\x80, tail]\n'
  printf 'after: end\n'
} > "${unicode}"

# ---------------------------------------------------------------------------
# Verification. Each assertion is on the raw bytes, not on parsed content.
# ---------------------------------------------------------------------------
fail=0

check() {
  local label="$1" expected="$2" actual="$3"
  if [[ "${expected}" == "${actual}" ]]; then
    printf 'ok   %s\n' "${label}"
  else
    printf 'FAIL %s: expected %s, got %s\n' "${label}" "${expected}" "${actual}" >&2
    fail=1
  fi
} # End of function check()

crlf_count=$(od -An -tx1 -v "${crlf}" | tr ' ' '\n' | grep -c '^0d$' || true)
lf_count=$(od -An -tx1 -v "${crlf}" | tr ' ' '\n' | grep -c '^0a$' || true)
check "crlf: every LF is preceded by a CR" "${lf_count}" "${crlf_count}"

bom_head=$(od -An -tx1 -N3 -v "${bom}" | tr -d ' \n')
check "bom: first three bytes" "efbbbf" "${bom_head}"

last_byte=$(tail -c 1 "${no_newline}" | od -An -tx1 | tr -d ' \n')
check "no-trailing-newline: last byte is an apostrophe (0x27)" "27" "${last_byte}"

crlf_in_bom=$(od -An -tx1 -v "${bom}" | tr ' ' '\n' | grep -c '^0d$' || true)
check "bom: contains no CR bytes" "0" "${crlf_in_bom}"

unicode_hex=$(od -An -tx1 -v "${unicode}" | tr -d ' \n')
case "${unicode_hex}" in
  *65cc81*) check "unicode: decomposed é is still 65 cc 81" "ok" "ok" ;;
  *)        check "unicode: decomposed é is still 65 cc 81" "ok" "NORMALISED" ;;
esac
case "${unicode_hex}" in
  *c3a9*) check "unicode: precomposed é is still c3 a9" "ok" "ok" ;;
  *)      check "unicode: precomposed é is still c3 a9" "ok" "missing" ;;
esac
case "${unicode_hex}" in
  *f09f9880*) check "unicode: astral emoji is still f0 9f 98 80" "ok" "ok" ;;
  *)          check "unicode: astral emoji is still f0 9f 98 80" "ok" "missing" ;;
esac

printf '\n--- %s ---\n' "$(basename "${crlf}")"
od -c "${crlf}" | head -6
printf '\n--- %s ---\n' "$(basename "${bom}")"
od -c "${bom}" | head -3
printf '\n--- %s (tail) ---\n' "$(basename "${no_newline}")"
od -c "${no_newline}" | tail -4
printf '\n--- %s (tail) ---\n' "$(basename "${unicode}")"
od -c "${unicode}" | tail -4

exit "${fail}"
