#!/usr/bin/env bash
#
# Regenerate the byte-exact corpus fixtures.
#
# These files cannot be authored with a normal editor: every editor on this
# machine will helpfully "fix" a CRLF file, strip a BOM, or add the missing
# final newline. So they are generated by `printf` with explicit escapes and
# verified byte-for-byte here.
#
# Run from anywhere:
#     ./scripts/build-byte-exact-fixtures.sh
#
# The script is idempotent and prints an `od -c` dump of each result so a human
# can confirm the bytes are what the file name claims.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
corpus="${repo_root}/crates/espansoconfig-core/tests/corpus/synthetic"
mkdir -p "${corpus}"

# ---------------------------------------------------------------------------
# 1. CRLF line endings, including inside a literal block scalar.
#
# YAML normalises line breaks to LF when it decodes a scalar, so the decoded
# value of the block below differs from its source bytes. Any code that writes
# a decoded value straight back would silently convert this file to LF.
# ---------------------------------------------------------------------------
crlf="${corpus}/crlf-line-endings.yml"
printf '%s\r\n' \
  '# CRLF fixture — every line break in this file is \r\n.' \
  '# Do NOT let an editor normalise it. See README.md in this directory.' \
  'matches:' \
  '  - trigger: :crlf' \
  '    replace: single line with a CRLF terminator' \
  '' \
  '  - trigger: :crlf-block' \
  '    replace: |' \
  '      first block line' \
  '      second block line' \
  '' \
  '  - trigger: :crlf-quoted' \
  "    replace: 'quoted value, CRLF after it'" \
  > "${crlf}"

# ---------------------------------------------------------------------------
# 2. UTF-8 BOM (EF BB BF) at the very start of the file.
#
# Espanso tolerates a BOM. We must strip it before parsing, remember it, and
# write it back on save — dropping it is a one-byte data loss that shows up as
# a diff in the user's git history.
# ---------------------------------------------------------------------------
bom="${corpus}/bom-utf8.yml"
{
  printf '\xEF\xBB\xBF'
  printf '%s\n' \
    '# UTF-8 BOM fixture — the first three bytes are EF BB BF.' \
    '# Do NOT let an editor strip them. See README.md in this directory.' \
    'matches:' \
    '  - trigger: :bom' \
    "    replace: 'the file starts with a byte-order mark'" \
    '  - trigger: :bom-acentos' \
    "    replace: 'áéíóú after a BOM'"
} > "${bom}"

# ---------------------------------------------------------------------------
# 3. No trailing newline.
#
# The last byte is `'`, not \n. A save that appends a newline "to be tidy"
# breaks the byte-identity guarantee on a file the user never edited.
# ---------------------------------------------------------------------------
no_newline="${corpus}/no-trailing-newline.yml"
{
  printf '%s\n' \
    '# No-trailing-newline fixture — the last byte of this file is an' \
    "# apostrophe, not a line feed. Do NOT let an editor add one." \
    'matches:' \
    '  - trigger: :no-final-newline'
  printf '%s' "    replace: 'the last line has no terminator'"
} > "${no_newline}"

# ---------------------------------------------------------------------------
# 4. Unicode offset-counting probe.
#
# The second sequence element must be a DECOMPOSED e + U+0301, not a
# precomposed U+00E9. Typing it in an editor, or letting one "clean up" the
# file, silently normalises it to NFC — and that destroys the only case that
# separates Unicode scalar values from grapheme clusters.
# ---------------------------------------------------------------------------
unicode="${corpus}/unicode-offsets.yml"
{
  printf '%s\n' \
    '# Offset-counting probe. Do NOT normalise this file.' \
    '# Element 1 is PRECOMPOSED U+00E9. Element 2 is DECOMPOSED U+0065 U+0301.' \
    '# Element 3 is U+1F600, outside the Basic Multilingual Plane.' \
    '# Together they distinguish byte / scalar-value / UTF-16 / grapheme offsets.'
  printf 'probe: [\xC3\xA9, e\xCC\x81, \xF0\x9F\x98\x80, tail]\n'
  printf 'after: end\n'
} > "${unicode}"

# ---------------------------------------------------------------------------
# 5. Terminal spaces at end-of-source, inside a block scalar.
#
# The last two bytes are spaces and there is no final newline. Because nothing
# follows the block scalar, those spaces cannot be the indentation of a next
# token: they are scalar CONTENT. An editor that trims trailing whitespace
# shortens the value by two characters without leaving a trace.
# ---------------------------------------------------------------------------
terminal="${corpus}/block-scalar-terminal-spaces.yml"
{
  printf '%s\n' \
    '# A block scalar whose last content line ends in GENUINE TRAILING SPACES, at' \
    '# the very end of the file.' \
    '#' \
    '# There is no next token after it, so those spaces cannot be the indentation of' \
    '# whatever comes next: they are scalar CONTENT, and a trim that removes them' \
    "# shortens the user's expansion by two characters. The file also has no final" \
    '# newline, which is what puts the block scalar at end-of-source.' \
    '#' \
    '# `tests/corpus_integrity.rs` fails if an editor trims the trailing spaces or' \
    '# adds a final newline.' \
    'matches:' \
    '  - trigger: :ordinary' \
    '    replace: |' \
    '      an ordinary block with a normal ending' \
    '    label: after-ordinary' \
    '' \
    '  - trigger: :terminal-spaces' \
    '    replace: |'
  printf '%s' '      two real spaces end this line  '
} > "${terminal}"

# ---------------------------------------------------------------------------
# 6. A file-owned comment inside a removable collection, mixed line endings,
#    and no final break.
#
# Added by the Phase 0c-3a review's fix round, for two demonstrated defects the
# corpus could not see:
#
#   * finding 1 — an entry whose value is a collection with a FILE-owned comment
#     between two of its descendants. The removal envelope is a contiguous hull,
#     so it crosses that comment although no node owns it, and every layer of
#     verification used to certify the result;
#   * finding 2 — most of this file ends its lines with a bare LF and two lines
#     end with CRLF, so the document-wide "dominant" ending is LF while the
#     anchor an insertion must copy is CRLF. An insertion that consults the
#     document instead of the anchor writes the wrong bytes here.
#
# The file also has no final line break, so an insertion at end of file has to
# learn its ending from a sibling rather than from a terminator that is not
# there.
# ---------------------------------------------------------------------------
mixed="${corpus}/file-comments-and-mixed-endings.yml"
{
  printf '%s\n' \
    '# Structural-edit shapes neither corpus had. This file BYTES are the test:' \
    '# most lines end with a bare LF, two end with CRLF, and the file has no final' \
    '# line break at all. Do NOT let an editor normalise any of that.' \
    'matches:' \
    "  - trigger: ':interior-file-comment'" \
    '    vars:' \
    "      first: 'one'" \
    '      # A blank line separates this comment from what follows, so the' \
    '      # ownership rules give it to the FILE. Removing the vars entry that' \
    '      # contains it must not take it away.' \
    '' \
    "      second: 'two'" \
    "    replace: 'the entry above carries a comment the file owns'" \
    ''
  printf '%s\r\n' \
    "  - trigger: ':crlf-anchor'" \
    "    replace: 'this line ends with CRLF although the file is mostly LF'"
  printf '%s\n' \
    "    label: 'an entry inserted after either line above must end with CRLF'" \
    '' \
    "  - trigger: ':ends-the-file'"
  printf '%s' "    replace: 'nothing terminates this line'"
} > "${mixed}"

# ---------------------------------------------------------------------------
# 7. A document that supplies NO line-ending evidence at all.
#
# One line, no final break. `LineEnding::detect` answers LF for it — by
# defaulting, not by measuring — and an insertion that trusted that answer would
# write a line ending this file never contained (the Phase 0c-3a review's
# finding 2). The engine refuses instead, and this fixture is what makes that
# refusal reachable from corpus data rather than only from a unit test.
#
# It deliberately carries no explanatory header: a comment line would add the
# very line break the fixture exists not to have. The explanation lives here, in
# `tests/corpus_integrity.rs`, and in `docs/decisions/0c-3a-notes.md`.
# ---------------------------------------------------------------------------
single="${corpus}/single-line-no-line-ending.yml"
printf '%s' "only: 'one entry, one line, and no line break anywhere'" > "${single}"

# ---------------------------------------------------------------------------
# Verification. Each assertion is on the raw bytes, not on parsed content.
# ---------------------------------------------------------------------------
fail=0

check() {
  local label="$1" expected="$2" actual="$3"
  if [[ "${expected}" == "${actual}" ]]; then
    printf 'ok   %s\n' "${label}"
  else
    printf 'FAIL %s: expected %s, got %s\n' "${label}" "${expected}" "${actual}" >&2
    fail=1
  fi
} # End of function check()

crlf_count=$(od -An -tx1 -v "${crlf}" | tr ' ' '\n' | grep -c '^0d$' || true)
lf_count=$(od -An -tx1 -v "${crlf}" | tr ' ' '\n' | grep -c '^0a$' || true)
check "crlf: every LF is preceded by a CR" "${lf_count}" "${crlf_count}"

bom_head=$(od -An -tx1 -N3 -v "${bom}" | tr -d ' \n')
check "bom: first three bytes" "efbbbf" "${bom_head}"

last_byte=$(tail -c 1 "${no_newline}" | od -An -tx1 | tr -d ' \n')
check "no-trailing-newline: last byte is an apostrophe (0x27)" "27" "${last_byte}"

crlf_in_bom=$(od -An -tx1 -v "${bom}" | tr ' ' '\n' | grep -c '^0d$' || true)
check "bom: contains no CR bytes" "0" "${crlf_in_bom}"

unicode_hex=$(od -An -tx1 -v "${unicode}" | tr -d ' \n')
case "${unicode_hex}" in
  *65cc81*) check "unicode: decomposed é is still 65 cc 81" "ok" "ok" ;;
  *)        check "unicode: decomposed é is still 65 cc 81" "ok" "NORMALISED" ;;
esac
case "${unicode_hex}" in
  *c3a9*) check "unicode: precomposed é is still c3 a9" "ok" "ok" ;;
  *)      check "unicode: precomposed é is still c3 a9" "ok" "missing" ;;
esac
case "${unicode_hex}" in
  *f09f9880*) check "unicode: astral emoji is still f0 9f 98 80" "ok" "ok" ;;
  *)          check "unicode: astral emoji is still f0 9f 98 80" "ok" "missing" ;;
esac

terminal_tail=$(tail -c 3 "${terminal}" | od -An -tx1 | tr -d ' \n')
check "terminal-spaces: last three bytes end in two spaces" "652020" "${terminal_tail}"

mixed_crlf=$(od -An -tx1 -v "${mixed}" | tr ' ' '\n' | grep -c '^0d$' || true)
mixed_lf=$(od -An -tx1 -v "${mixed}" | tr ' ' '\n' | grep -c '^0a$' || true)
check "mixed: exactly two CRLF line endings" "2" "${mixed_crlf}"
if (( mixed_lf > mixed_crlf + 2 )); then
  check "mixed: bare LF endings outnumber CRLF ones" "ok" "ok"
else
  check "mixed: bare LF endings outnumber CRLF ones" "ok" "NORMALISED"
fi
mixed_last=$(tail -c 1 "${mixed}" | od -An -tx1 | tr -d ' \n')
check "mixed: last byte is an apostrophe (0x27)" "27" "${mixed_last}"

single_breaks=$(od -An -tx1 -v "${single}" | tr ' ' '\n' | grep -cE '^(0a|0d)$' || true)
check "single-line: contains no line break at all" "0" "${single_breaks}"

printf '\n--- %s ---\n' "$(basename "${crlf}")"
od -c "${crlf}" | head -6
printf '\n--- %s ---\n' "$(basename "${bom}")"
od -c "${bom}" | head -3
printf '\n--- %s (tail) ---\n' "$(basename "${no_newline}")"
od -c "${no_newline}" | tail -4
printf '\n--- %s (tail) ---\n' "$(basename "${unicode}")"
od -c "${unicode}" | tail -4
printf '\n--- %s (tail) ---\n' "$(basename "${terminal}")"
od -c "${terminal}" | tail -3
printf '\n--- %s (tail) ---\n' "$(basename "${mixed}")"
od -c "${mixed}" | tail -6

exit "${fail}"
